SELECT K.NR_BANDY
FROM KOCURY K
WHERE K.NR_BANDY IN (
  SELECT K2.NR_BANDY
  FROM KOCURY K2 FULL JOIN WROGOWIE_KOCUROW WK FULL JOIN WROGOWIE W
  WHERE K2.PSEUDO = WK.PSEUDO AND
        WK.IMIE_WROGA = W.IMIE_WROGA
        AND 3 > (SELECT COUNT(*)
                 FROM WROGOWIE W1
                 WHERE W1.STOPIEN_WROGOSCI > W.STOPIEN_WROGOSCI)
  GROUP BY K2.NR_BANDY
  HAVING COUNT(DISTINCT W.IMIE_WROGA) = 2
)
GROUP BY K.NR_BANDY
HAVING COUNT(*) > 4;


SELECT K.NR_BANDY
FROM KOCURY K
WHERE K.NR_BANDY IN (
  SELECT K2.NR_BANDY
  FROM KOCURY K2
    JOIN WROGOWIE_KOCUROW WK ON K2.PSEUDO = WK.PSEUDO
    JOIN WROGOWIE W ON WK.IMIE_WROGA = W.IMIE_WROGA
  WHERE W.IMIE_WROGA IN (
    SELECT W3.IMIE_WROGA
    FROM WROGOWIE W3 FULL JOIN WROGOWIE W4
        ON W3.STOPIEN_WROGOSCI > W4.STOPIEN_WROGOSCI
    GROUP BY W3.IMIE_WROGA
    HAVING COUNT(*) < 3
  )
  GROUP BY K2.NR_BANDY
  HAVING COUNT(DISTINCT W.IMIE_WROGA) = 2
)
GROUP BY K.NR_BANDY
HAVING COUNT(*) > 4;


SELECT
  PSEUDO,
  NR_BANDY
FROM KOCURY K1
WHERE PLEC = 'M'
      AND 55 <= (SELECT AVG(PRZYDZIAL_MYSZY)
                 FROM KOCURY K2
                 WHERE PLEC = 'M'
                 GROUP BY NR_BANDY
                 HAVING K2.NR_BANDY = K1.NR_BANDY)
MINUS
SELECT
  PSEUDO,
  NR_BANDY
FROM KOCURY
  JOIN WROGOWIE_KOCUROW USING (PSEUDO);


SELECT
  PSEUDO,
  NR_BANDY
FROM (SELECT
        PSEUDO,
        NR_BANDY,
        AVG(K.PRZYDZIAL_MYSZY)
        OVER (
          PARTITION BY K.NR_BANDY ) AVER
      FROM KOCURY K
        LEFT JOIN WROGOWIE_KOCUROW WK ON K.PSEUDO = WK.PSEUDO
      WHERE K.PLEC = 'M' AND WK.IMIE_WROGA IS NULL
)
WHERE AVER >= 55;

--       AND 55 <= (SELECT AVG(PRZYDZIAL_MYSZY)
--                  FROM KOCURY K2
--                  WHERE K.PLEC = 'M')

SELECT
  pseudo,
  nr_bandy
FROM Kocury k1
WHERE plec = 'M'
      and 55 <= (SELECT avg(przydzial_myszy)
                FROM Kocury k2
                WHERE plec = 'M'
                GROUP BY nr_bandy
                HAVING k2.nr_bandy = k1.nr_bandy)
MINUS
SELECT
  pseudo,
  nr_bandy
FROM Kocury JOIN Wrogowie_Kocurow USING(pseudo);

