--17--
SELECT
  PSEUDO          "POLUJE W POLU",
  PRZYDZIAL_MYSZY "PRYDZIAL MYSZY",
  NAZWA
FROM KOCURY K
  JOIN BANDY B ON K.NR_BANDY = B.NR_BANDY
WHERE K.PRZYDZIAL_MYSZY > 50 AND B.TEREN IN ('POLE', 'CALOSC');

--18--
SELECT
  K.IMIE                               "IMIE",
  TO_CHAR(K.W_STADKU_OD, 'YYYY-MM-DD') "POLUJE OD"
FROM KOCURY K
  JOIN KOCURY KJ ON K.W_STADKU_OD < KJ.W_STADKU_OD AND KJ.IMIE = 'JACEK'
ORDER BY K.W_STADKU_OD DESC;

--19--

--20--
SELECT
  K.IMIE       "IMIE KOTKI",
  B.NAZWA      "NAZWA BANDY",
  WK.IMIE_WROGA "IMIE WROGA",
  W.STOPIEN_WROGOSCI "OCENA WROGA",
  WK.DATA_INCYDENTU "Data inc."
FROM KOCURY K
  JOIN WROGOWIE_KOCUROW WK ON K.PSEUDO = WK.PSEUDO
  JOIN BANDY B ON K.NR_BANDY = B.NR_BANDY
  JOIN WROGOWIE W ON W.IMIE_WROGA = WK.IMIE_WROGA
WHERE K.PLEC = 'D' AND WK.DATA_INCYDENTU > TO_DATE('2007-01-01', 'YYYY-MM-DD');

--21--
SELECT
  B.NAZWA "Nazwa bandy",

FROM BANDY B;